import { app, BrowserWindow, ipcMain, dialog, session } from "electron";
import updater from "electron-updater";
import { spawn, execFile } from "child_process";
import fs from "fs";
import https from "https";
import path from "path";
import { fileURLToPath } from "url";

// ESM: tự định nghĩa __dirname từ import.meta.url
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const { autoUpdater } = updater;

type DownloadFormat = "mp3" | "mp4";
type DownloadQuality = "best" | "720p" | "1080p";

interface DownloadOptions {
  url: string;
  format: DownloadFormat;
  quality: DownloadQuality;
  outputDir?: string;
  outputTemplate?: string;
  cookiesFilePath?: string;
  cookiesFromBrowser?: "chrome" | "edge";
}

type DownloadStatus = "idle" | "queued" | "downloading" | "completed" | "error";

interface DownloadStatusPayload {
  status: DownloadStatus;
  message?: string;
}

interface DownloadProgressPayload {
  percent: number;
}

type UpdateState =
  | "idle"
  | "checking"
  | "available"
  | "not-available"
  | "downloading"
  | "downloaded"
  | "error";

interface UpdateStatusPayload {
  state: UpdateState;
  message?: string;
  percent?: number;
  version?: string;
}

let mainWindow: BrowserWindow | null = null;
let authWindow: BrowserWindow | null = null;

const isDev = !app.isPackaged;

// Regex lấy % từ dòng progress của yt-dlp: [download]  12.5% of ...
const PROGRESS_REGEX = /\[download\]\s+(\d+\.?\d*)%/;

const AUTH_PARTITION = "persist:media-auth";

function normalizeVideoUrl(input: string): string {
  // Một số trang Douyin (vd /jingxuan/...) mở video qua modal_id, yt-dlp thường không nhận dạng URL này.
  // Chuẩn hoá về URL video trực tiếp: https://www.douyin.com/video/<id>
  try {
    const u = new URL(input);
    const host = u.hostname.replace(/^www\./, "");
    if (host === "douyin.com") {
      const modalId = u.searchParams.get("modal_id");
      if (modalId && /^\d+$/.test(modalId)) {
        return `https://www.douyin.com/video/${modalId}`;
      }
    }
  } catch {
    // ignore parse errors; return original
  }
  return input;
}

function getHost(input: string): string {
  try {
    return new URL(input).hostname.replace(/^www\./, "").toLowerCase();
  } catch {
    return "";
  }
}

function isDouyinOrTikTokUrl(input: string): boolean {
  const host = getHost(input);
  return host.endsWith("douyin.com") || host.endsWith("tiktok.com");
}

function toNetscapeCookieLine(c: Electron.Cookie): string {
  const domain = (c.domain ?? "").startsWith(".") ? (c.domain ?? "") : (c.domain ?? "");
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const pathValue = c.path || "/";
  const secure = c.secure ? "TRUE" : "FALSE";
  // expirationDate is seconds since UNIX epoch; if absent (session cookie) use 0
  const expires = typeof c.expirationDate === "number" ? Math.floor(c.expirationDate) : 0;
  const name = c.name;
  const value = c.value;
  return `${domain}\t${includeSubdomains}\t${pathValue}\t${secure}\t${expires}\t${name}\t${value}`;
}

async function exportAuthCookiesForUrl(url: string): Promise<string | null> {
  if (!isDouyinOrTikTokUrl(url)) return null;

  const host = getHost(url);
  const authSes = session.fromPartition(AUTH_PARTITION);

  // Collect cookies for main domain and dot-prefixed domain
  const baseDomain = host.replace(/^.*?(\w+\.\w+)$/, "$1");
  const domains = Array.from(
    new Set<string>([host, `.${host}`, baseDomain, `.${baseDomain}`].filter(Boolean)),
  );

  const cookies: Electron.Cookie[] = [];
  for (const d of domains) {
    // Electron expects domain without scheme in filter
    const list = await authSes.cookies.get({ domain: d });
    cookies.push(...list);
  }

  const unique = new Map<string, Electron.Cookie>();
  for (const c of cookies) {
    unique.set(`${c.domain}|${c.path}|${c.name}`, c);
  }

  if (unique.size === 0) return null;

  const outDir = path.join(app.getPath("userData"), "cookies");
  fs.mkdirSync(outDir, { recursive: true });
  const outPath = path.join(outDir, host.endsWith("douyin.com") ? "douyin.cookies.txt" : "tiktok.cookies.txt");

  const header =
    "# Netscape HTTP Cookie File\n" +
    "# This file was generated by Media Downloader (Electron).\n" +
    "# DO NOT SHARE THIS FILE.\n\n";
  const body = Array.from(unique.values()).map(toNetscapeCookieLine).join("\n") + "\n";
  fs.writeFileSync(outPath, header + body, "utf8");
  return outPath;
}

function createWindow(): void {
  const preloadPath = path.resolve(__dirname, "preload.cjs");

  mainWindow = new BrowserWindow({
    width: 1000,
    height: 700,
    webPreferences: {
      preload: preloadPath,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
    },
  });

  // Luôn load renderer từ file build để dự án này chỉ phục vụ bản desktop (exe).
  // Dev workflow: chạy "npm run dev" (build renderer + main) rồi mở Electron.
  mainWindow.loadFile(path.join(__dirname, "../renderer/index.html"));
  if (isDev) {
    mainWindow.webContents.openDevTools({ mode: "detach" });
  }
}

function openAuthWindow(target: "douyin" | "tiktok"): void {
  if (authWindow && !authWindow.isDestroyed()) {
    authWindow.focus();
    return;
  }

  const preloadPath = path.resolve(__dirname, "preload.cjs");
  const authSes = session.fromPartition(AUTH_PARTITION);

  authWindow = new BrowserWindow({
    width: 1100,
    height: 800,
    title: target === "douyin" ? "Đăng nhập Douyin" : "Đăng nhập TikTok",
    webPreferences: {
      // Reuse preload is fine; contextBridge does not expose Node APIs
      preload: preloadPath,
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: false,
      session: authSes,
    },
  });

  const url = target === "douyin" ? "https://www.douyin.com/" : "https://www.tiktok.com/";
  void authWindow.loadURL(url);

  authWindow.on("closed", () => {
    authWindow = null;
  });
}

function sendToRenderer(channel: string, payload: unknown): void {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send(channel, payload);
  }
}

function resolveToolPath(executable: "yt-dlp.exe" | "ffmpeg.exe"): string {
  // Ưu tiên thư mục tools đóng gói cùng app (prod) hoặc nằm trong project (dev)
  const bundledToolsDir = isDev
    ? path.join(__dirname, "..", "..", "tools")
    : path.join(process.resourcesPath, "tools");

  const bundledPath = path.join(bundledToolsDir, executable);
  if (fs.existsSync(bundledPath)) {
    return bundledPath;
  }

  // Hỗ trợ fallback cho trường hợp bạn đặt ở C:\tools
  const driveToolsDir = path.join("C:\\", "tools");

  if (executable === "yt-dlp.exe") {
    const ytDlpPath = path.join(driveToolsDir, "yt-dlp.exe");
    if (fs.existsSync(ytDlpPath)) {
      return ytDlpPath;
    }
  }

  if (executable === "ffmpeg.exe") {
    // Một số bản ffmpeg giải nén thành C:\tools\ffmpeg\bin\ffmpeg.exe
    const candidates = [
      path.join(driveToolsDir, "ffmpeg.exe"),
      path.join(driveToolsDir, "ffmpeg", "ffmpeg.exe"),
      path.join(driveToolsDir, "ffmpeg", "bin", "ffmpeg.exe"),
    ];
    const found = candidates.find((p) => fs.existsSync(p));
    if (found) {
      return found;
    }
  }

  // Nếu không tìm được, trả về đường dẫn mặc định (sẽ báo lỗi ENOENT rõ ràng)
  return bundledPath;
}

function getDevToolsDir(): string {
  // Dev only: tools nằm ở root project (../.. từ dist/main)
  return path.join(__dirname, "..", "..", "tools");
}

async function getYtDlpVersion(): Promise<string | null> {
  const ytDlpPath = resolveToolPath("yt-dlp.exe");
  if (!fs.existsSync(ytDlpPath)) return null;
  return await new Promise((resolve) => {
    execFile(ytDlpPath, ["--version"], { windowsHide: true }, (err, stdout) => {
      if (err) return resolve(null);
      const v = String(stdout ?? "").trim();
      resolve(v || null);
    });
  });
}

async function downloadToFile(url: string, destPath: string): Promise<void> {
  const tmpPath = destPath + ".tmp";
  await new Promise<void>((resolve, reject) => {
    const doRequest = (u: string, redirectsLeft: number) => {
      https
        .get(
          u,
          {
            headers: {
              "User-Agent": "media-desktop-app-dev",
              Accept: "*/*",
            },
          },
          (res) => {
            const status = res.statusCode ?? 0;
            const loc = res.headers.location;
            if (status >= 300 && status < 400 && loc && redirectsLeft > 0) {
              res.resume();
              const next = loc.startsWith("http") ? loc : new URL(loc, u).toString();
              doRequest(next, redirectsLeft - 1);
              return;
            }
            if (status < 200 || status >= 300) {
              res.resume();
              reject(new Error(`HTTP ${status}`));
              return;
            }

            const file = fs.createWriteStream(tmpPath);
            res.pipe(file);
            file.on("finish", () => {
              file.close(() => resolve());
            });
            file.on("error", (err) => reject(err));
          },
        )
        .on("error", (err) => reject(err));
    };
    doRequest(url, 5);
  });

  const stat = fs.statSync(tmpPath);
  if (!stat.size) {
    fs.unlinkSync(tmpPath);
    throw new Error("Downloaded file is empty");
  }

  fs.renameSync(tmpPath, destPath);
}

function parseProgress(text: string): void {
  const lines = text.split(/\r?\n/);
  for (const line of lines) {
    const match = PROGRESS_REGEX.exec(line);
    if (match) {
      const percent = Math.min(100, Number.parseFloat(match[1]));
      const payload: DownloadProgressPayload = { percent };
      sendToRenderer("download:progress", payload);
    }
  }
}

function buildYtDlpArgs(options: DownloadOptions): {
  executable: string;
  args: string[];
} {
  const ytDlpPath = resolveToolPath("yt-dlp.exe");
  const ffmpegPath = resolveToolPath("ffmpeg.exe");

  const host = getHost(options.url);
  const isTikTok = host.endsWith("tiktok.com");

  const args: string[] = [
    options.url,
    "-o",
    options.outputTemplate ?? path.join(options.outputDir ?? app.getPath("downloads"), "%(title)s.%(ext)s"),
    "--newline",
    "--no-warnings",
    "--ffmpeg-location",
    ffmpegPath,
  ];

  if (isTikTok) {
    // Giảm khả năng bị 403 khi tải TikTok
    args.push("--add-header", "Referer:https://www.tiktok.com/");
    args.push("--add-header", "Accept-Language:en-US,en;q=0.9");
    args.push(
      "--user-agent",
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    );
  }

  // Một số nền tảng (Douyin/TikTok/FB/IG...) cần cookies để tải ổn định
  if (options.cookiesFromBrowser) {
    args.push("--cookies-from-browser", options.cookiesFromBrowser);
  } else if (options.cookiesFilePath) {
    args.push("--cookies", options.cookiesFilePath);
  }

  if (options.format === "mp3") {
    // Tách audio và convert sang MP3
    args.push("-x", "--audio-format", "mp3", "--audio-quality", "0");
  } else {
    // MP4 video với các mức chất lượng khác nhau
    let formatSelector: string;
    switch (options.quality) {
      case "720p":
        formatSelector =
          "bv*[height<=720][ext=mp4]+ba[ext=m4a]/best[height<=720][ext=mp4]/best[height<=720]";
        break;
      case "1080p":
        formatSelector =
          "bv*[height<=1080][ext=mp4]+ba[ext=m4a]/best[height<=1080][ext=mp4]/best[height<=1080]";
        break;
      case "best":
      default:
        formatSelector = "bv*[ext=mp4]+ba[ext=m4a]/best[ext=mp4]/best";
        break;
    }
    args.push("-f", formatSelector);
  }

  return { executable: ytDlpPath, args };
}

function registerIpcHandlers(): void {
  // Thông tin app cho renderer (version, v.v.)
  ipcMain.handle("app:get-info", async () => {
    return {
      version: app.getVersion(),
      isDev,
      ytDlpVersion: await getYtDlpVersion(),
    };
  });

  // Chọn thư mục lưu file
  ipcMain.handle("select-folder", async () => {
    if (!mainWindow) return null;

    const result = await dialog.showOpenDialog(mainWindow, {
      properties: ["openDirectory"],
    });
    if (result.canceled) return null;
    return result.filePaths[0] ?? null;
  });

  // Chọn file (vd: cookies.txt)
  ipcMain.handle("select-file", async (_event, options?: { title?: string; filters?: { name: string; extensions: string[] }[] }) => {
    if (!mainWindow) return null;
    const result = await dialog.showOpenDialog(mainWindow, {
      title: options?.title,
      properties: ["openFile"],
      filters: options?.filters,
    });
    if (result.canceled) return null;
    return result.filePaths[0] ?? null;
  });

  // Cho phép user bấm nút để đóng Chrome/Edge khi cookies DB bị khóa.
  // Không chạy tự động để tránh gây khó chịu / mất dữ liệu.
  ipcMain.handle("system:close-browsers", async () => {
    const cmds: Array<{ name: string; args: string[] }> = [
      { name: "taskkill", args: ["/IM", "msedge.exe", "/F"] },
      { name: "taskkill", args: ["/IM", "chrome.exe", "/F"] },
    ];

    await Promise.all(
      cmds.map(
        (c) =>
          new Promise<void>((resolve) => {
            execFile(c.name, c.args, () => resolve());
          }),
      ),
    );
  });

  ipcMain.handle("auth:open", async (_event, target: "douyin" | "tiktok") => {
    openAuthWindow(target);
  });

  // Dev-only: tải/cập nhật yt-dlp.exe bản mới nhất từ nguồn chính thức.
  ipcMain.handle("dev:yt-dlp:update", async () => {
    if (!isDev) {
      throw new Error("Dev-only");
    }
    const toolsDir = getDevToolsDir();
    fs.mkdirSync(toolsDir, { recursive: true });
    const dest = path.join(toolsDir, "yt-dlp.exe");
    const url = "https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe";
    await downloadToFile(url, dest);
    return {
      path: dest,
      version: await getYtDlpVersion(),
    };
  });

  // Bắt đầu tải
  ipcMain.handle("download", async (_event, rawOptions: DownloadOptions) => {
    const trimmedUrl = normalizeVideoUrl(rawOptions?.url?.trim() ?? "");

    if (!trimmedUrl) {
      const error = "URL không hợp lệ.";
      const payload: DownloadStatusPayload = {
        status: "error",
        message: error,
      };
      sendToRenderer("download:status", payload);
      throw new Error(error);
    }

    const format: DownloadFormat = rawOptions.format ?? "mp4";
    const quality: DownloadQuality = rawOptions.quality ?? "best";
    const outputDir = rawOptions.outputDir || app.getPath("downloads");
    const outputTemplate = path.join(outputDir, "%(title)s.%(ext)s");
    let cookiesFilePath = rawOptions.cookiesFilePath?.trim() || undefined;
    const cookiesFromBrowser = rawOptions.cookiesFromBrowser;

    // Ưu tiên cookies từ cửa sổ đăng nhập trong app cho Douyin/TikTok (tránh DPAPI issues của Edge/Chrome).
    if (!cookiesFilePath && isDouyinOrTikTokUrl(trimmedUrl)) {
      cookiesFilePath = (await exportAuthCookiesForUrl(trimmedUrl)) ?? undefined;
    }

    const options: DownloadOptions = {
      url: trimmedUrl,
      format,
      quality,
      outputDir,
      outputTemplate,
      cookiesFilePath,
      cookiesFromBrowser,
    };

    const queuedPayload: DownloadStatusPayload = {
      status: "queued",
      message: "Đang chuẩn bị tải...",
    };
    sendToRenderer("download:status", queuedPayload);

    return new Promise<string>((resolve, reject) => {
      const { executable, args } = buildYtDlpArgs(options);

      const downloadingPayload: DownloadStatusPayload = {
        status: "downloading",
        message: "Đang tải...",
      };
      sendToRenderer("download:status", downloadingPayload);

      let lastMessage = "";

      const child = spawn(executable, args, {
        windowsHide: true,
      });

      child.stdout.on("data", (data: Buffer) => {
        const text = data.toString();
        parseProgress(text);
      });

      child.stderr.on("data", (data: Buffer) => {
        const text = data.toString();
        lastMessage = text.trim() || lastMessage;
        parseProgress(text);
      });

      child.on("error", (err: NodeJS.ErrnoException) => {
        let message = err.message;
        if (err.code === "ENOENT") {
          message =
            "Không tìm thấy yt-dlp hoặc ffmpeg. Đảm bảo có thư mục với yt-dlp.exe và ffmpeg.exe cạnh ứng dụng.";
        }

        const errorPayload: DownloadStatusPayload = {
          status: "error",
          message,
        };
        sendToRenderer("download:status", errorPayload);
        reject(new Error(message));
      });

      child.on("close", (code: number | null) => {
        if (code === 0) {
          const donePayload: DownloadStatusPayload = {
            status: "completed",
            message: "Tải hoàn tất.",
          };
          sendToRenderer("download:status", donePayload);
          const finalProgress: DownloadProgressPayload = { percent: 100 };
          sendToRenderer("download:progress", finalProgress);
          resolve("Tải hoàn tất.");
        } else {
          let message =
            lastMessage ||
            "Tải thất bại.";

          // Lỗi thường gặp khi dùng --cookies-from-browser (Chrome/Edge đang khóa DB cookies)
          if (
            /Could not copy Chrome cookie database/i.test(message) ||
            /Could not copy.*cookie database/i.test(message)
          ) {
            message =
              "Không đọc được cookies từ trình duyệt (Chrome/Edge có thể đang mở hoặc đang khóa dữ liệu). " +
              "Hãy đóng hoàn toàn Chrome/Edge rồi bấm Download lại.";
          }

          if (/Failed to decrypt with DPAPI/i.test(message)) {
            message =
              "Không đọc được cookies từ trình duyệt do Windows bảo vệ (DPAPI).\n" +
              "Cách nhanh nhất: bấm 'Đăng nhập Douyin' trong app, đăng nhập xong đóng cửa sổ đó, rồi bấm Download lại.";
          }

          // Gợi ý cập nhật yt-dlp khi extractor thay đổi (Douyin/TikTok thay đổi rất thường xuyên)
          if (/Unsupported URL/i.test(message) || /ExtractorError/i.test(message)) {
            message =
              message +
              "\n\nGợi ý: hãy cập nhật /tools/yt-dlp.exe lên bản mới nhất rồi thử lại.";
          }
          const errorPayload: DownloadStatusPayload = {
            status: "error",
            message,
          };
          sendToRenderer("download:status", errorPayload);
          reject(new Error(message));
        }
      });
    });
  });
}

function setupAutoUpdater(): void {
  if (isDev) {
    // Không bật auto-update trong môi trường dev
    const payload: UpdateStatusPayload = {
      state: "idle",
      message: "Chế độ phát triển — auto-update tắt.",
    };
    sendToRenderer("update:status", payload);
    return;
  }

  autoUpdater.autoDownload = true;

  autoUpdater.on("checking-for-update", () => {
    const payload: UpdateStatusPayload = {
      state: "checking",
      message: "Đang kiểm tra bản cập nhật...",
    };
    sendToRenderer("update:status", payload);
  });

  autoUpdater.on("update-available", (info) => {
    const payload: UpdateStatusPayload = {
      state: "available",
      version: info.version,
      message: `Đã tìm thấy bản cập nhật ${info.version}. Đang tải xuống...`,
    };
    sendToRenderer("update:status", payload);
  });

  autoUpdater.on("update-not-available", () => {
    const payload: UpdateStatusPayload = {
      state: "not-available",
      message: "Bạn đang dùng phiên bản mới nhất.",
    };
    sendToRenderer("update:status", payload);
  });

  autoUpdater.on("download-progress", (progress) => {
    const payload: UpdateStatusPayload = {
      state: "downloading",
      percent: progress.percent,
      message: `Đang tải bản cập nhật (${progress.percent.toFixed(1)}%)...`,
    };
    sendToRenderer("update:status", payload);
  });

  autoUpdater.on("update-downloaded", (info) => {
    const payload: UpdateStatusPayload = {
      state: "downloaded",
      version: info.version,
      message: "Bản cập nhật đã tải xong. Ứng dụng sẽ cập nhật khi khởi động lại.",
    };
    sendToRenderer("update:status", payload);
  });

  autoUpdater.on("error", (err) => {
    // Không hiển thị lỗi chi tiết cho user (404, app.yml, v.v.)
    const payload: UpdateStatusPayload = {
      state: "error",
      message: "Không thể kiểm tra cập nhật.",
    };
    sendToRenderer("update:status", payload);
  });

  void autoUpdater.checkForUpdates().catch(() => {
    const payload: UpdateStatusPayload = {
      state: "error",
      message: "Không thể kiểm tra cập nhật.",
    };
    sendToRenderer("update:status", payload);
  });
}

function registerUpdateHandlers(): void {
  ipcMain.handle("update:check", () => {
    if (isDev) return;
    void autoUpdater.checkForUpdates().catch(() => {});
  });

  ipcMain.handle("update:restart-and-install", () => {
    autoUpdater.quitAndInstall(false, true);
  });
}

app.whenReady().then(() => {
  createWindow();
  registerIpcHandlers();
  registerUpdateHandlers();
  setupAutoUpdater();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on("window-all-closed", () => {
  // Chỉ hỗ trợ Windows, nhưng vẫn giữ check cho an toàn
  if (process.platform !== "darwin") {
    app.quit();
  }
});